name: CI

on:
  workflow_call:
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  contents: write
  id-token: write
  security-events: write

jobs:
  # terraform-checks:
  #   name: "Terraform checks"
  #   uses: ./.github/workflows/terraform-checks.yaml
  #   with:
  #     terraform-directory: ${{ vars.TERRAFORM_DIRECTORY }}
  
  terraform-plan:
    name: "Terraform plan"
    secrets: inherit
    uses: ./.github/workflows/terraform-ci.yaml
    with:
      aws-role: ${{ vars.AWS_ROLE }}
      terraform-directory: ${{ vars.TERRAFORM_DIRECTORY }}

  test-database-migration:
    name: "Liquibase checks"
    secrets: inherit
    uses: ./.github/workflows/liquibase-ci.yaml
    with:
      aws-role: ${{ vars.AWS_ROLE }}
      db-name: ${{ vars.DB_NAME }}

  release-cd:
    name: "Deploy/Release API,Web"
    needs: test-database-migration
    secrets: inherit
    uses: ./.github/workflows/release-cd.yaml  
    with:
      aws-role: ${{ vars.AWS_ROLE }}
      account-id: ${{ vars.ACCOUNT_ID }}
      db-name: ${{ vars.DB_NAME }}