name: "Terraform Checks"

on:
  workflow_call:
    inputs:
      terraform-directory:
        required: true
        type: string

permissions:
  checks: write
  contents: read

jobs:
  terraform-checks:
    name: 'Terraform checks'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3.0.0

      - name: "Terraform fmt"
        working-directory: ${{ inputs.terraform-directory }}
        run: |
          terraform fmt -check --recursive .
        continue-on-error: false

      # - name: "Terraform security check"
      #   uses: aquasecurity/tfsec-action@v1.0.3
      #   with:
      #     working_directory: ${{ inputs.terraform-directory }}

      - name: "Setup tflint"
        uses: terraform-linters/setup-tflint@v4.0.0
        with:
          tflint_version: latest
      
      - name: "Run tflint"
        working-directory: ${{ inputs.terraform-directory }}
        run: |
          tflint -f compact